version: "3"
services:
  number_classifier_server:
    # перезапуск контейнера, в случае сбоя
    restart: always 
    container_name: number_classifier_server
    image: number_classifier_server
    # создание образа из Dockerfile из каталога сервера
    build: ./server
    # [порт компьютера]:[порт контейнера]
    ports:
      - 80:8000    
